title: Gadilingappagari kiran kumar 
logo: kiran passport size.png


theme: jekyll-theme-minimal

<a href="{{ site.baseurl }}/assets/resume.pdf" download="kiran_kumar_data_analyst_1.docx">
  Download My Resume
</a>
