title: Gadilingappagari Kiran Kumar
logo: kiran passport size.png
theme: jekyll-theme-minimal

show_downloads: true
resume: /assets/kiran_kumar_data_analyst_1.docx
download_link_html: 'Download My Resume <i class="fas fa-arrow-down"></i>'


